
//get Product list constants
export const GET_PRODUCTLIST_REQUEST = "GET_PRODUCTLIST_REQUEST"
export const GET_PRODUCTLIST_SUCCESS = "GET_PRODUCTLIST_SUCCESS"
export const GET_PRODUCTLIST_FAIL = "GET_PRODUCTLIST_FAIL"

//get Product constants
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

//cart constants
export const CART_ADD_REQUEST = "CART_ADD_REQUEST";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_REQUEST = "CART_REMOVE_REQUEST";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

//user constants
export const GET_SIGNIN_REQUEST = "GET_SIGNIN_REQUEST";
export const GET_SIGNIN_SUCCESS = "GET_SIGNIN_SUCCESS";
export const GET_SIGNIN_FAIL = "GET_SIGNIN_FAIL";
export const GET_SIGNOUT = "GET_SIGNOUT";
export const GET_SIGNOUT_REQUEST = "GET_SIGNOUT_REQUEST"

//user constants
export const GET_REGISTER_REQUEST = "GET_REGISTER_REQUEST";
export const GET_REGISTER_SUCCESS = "GET_REGISTER_SUCCESS";
export const GET_REGISTER_FAIL = "GET_REGISTER_FAIL";


//
export const SAVE_CHECKOUT_REQUEST = "SAVE_CHECKOUT_REQUEST";
export const SAVE_CHECKOUT_SUCCESS = "SAVE_CHECKOUT_SUCCESS";
export const SAVE_PAYMENT_SUCCESS = "SAVE_PAYMENT_SUCCESS";
export const SAVE_PAYMENT_REQUEST = "SAVE_PAYMENT_REQUEST";


export const SAVE_ORDER_REQUEST = "SAVE_ORDER_REQUEST";
export const SAVE_ORDER_SUCCESS = "SAVE_ORDER_SUCCESS";
export const SAVE_ORDER_FAIL = "SAVE_ORDER_FAIL";










